# Generated by Django 2.2.6 on 2019-11-04 13:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='distance',
            fields=[
                ('tid', models.BigAutoField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('destination', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='travel',
            fields=[
                ('tid', models.BigAutoField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=35)),
                ('source', models.CharField(max_length=50)),
                ('destination1', models.CharField(max_length=50)),
                ('destination2', models.CharField(max_length=50, null=True)),
                ('destination3', models.CharField(max_length=50, null=True)),
                ('destination4', models.CharField(max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True)),
                ('petrol_price', models.IntegerField()),
                ('total_cost', models.IntegerField()),
                ('bill', models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/bill'), upload_to='')),
            ],
        ),
    ]
