# Generated by Django 2.2.6 on 2019-11-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='petrol_price',
            field=models.IntegerField(default=75.13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='distance',
            name='source',
            field=models.CharField(default='source1', max_length=50),
        ),
        migrations.AlterField(
            model_name='travel',
            name='destination1',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='travel',
            name='destination2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='destination3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='destination4',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
