# Generated by Django 2.2.6 on 2019-11-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20191104_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distance',
            name='destination',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='source',
            field=models.CharField(default='source1', max_length=50, unique=True),
        ),
    ]
