# Generated by Django 2.2.6 on 2019-11-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20191104_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='petrol',
            fields=[
                ('tid', models.BigAutoField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('city', models.CharField(max_length=50, unique=True)),
                ('petrol_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='distance',
            name='petrol_price',
        ),
        migrations.AlterField(
            model_name='distance',
            name='source',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
