# Generated by Django 2.2.6 on 2019-11-04 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20191104_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petrol',
            old_name='city',
            new_name='state',
        ),
    ]
