# Generated by Django 2.2.6 on 2019-11-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20191104_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='distance',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='distance',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='destination',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='distance',
            name='source',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
