# Generated by Django 2.2.6 on 2019-11-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_auto_20191105_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='travel',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
            preserve_default=False,
        ),
    ]
