# Generated by Django 2.2.6 on 2019-11-06 12:11

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0008_travel_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='bill',
            field=models.ImageField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/bill/'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='travel',
            name='destination2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='destination3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='travel',
            name='destination4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
