# Generated by Django 2.2.6 on 2019-11-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_auto_20191106_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travel',
            name='bill',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
