# Generated by Django 2.2.6 on 2019-11-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_auto_20191106_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrol',
            name='petrol_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='petrol_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='travel',
            name='total_cost',
            field=models.FloatField(),
        ),
    ]
