# Generated by Django 2.2.6 on 2019-11-10 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='log',
            fields=[
                ('tid', models.BigAutoField(max_length=5, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('log', models.CharField(max_length=500)),
                ('fields', models.CharField(blank=True, max_length=500, null=True)),
                ('href', models.CharField(max_length=500)),
                ('go', models.CharField(max_length=500)),
            ],
        ),
    ]
