# Generated by Django 2.2.6 on 2019-11-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='log',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
