# Generated by Django 2.2.6 on 2019-11-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_auto_20191110_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='pfields',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='fields',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='log',
            name='tid',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
